// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epfqodeuufrjyibicdwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZnFvZGV1dWZyanlpYmljZHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTgzNDksImV4cCI6MjA1MDI5NDM0OX0.u37M21PtsZ-Hb3Qi05UaW3uNs66hH85fPbV2CM2XQMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);